set(TARGET_PUBLIC_PATH ${CMAKE_CURRENT_SOURCE_DIR}/public/onyx)
set(TARGET_PRIVATE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/private/onyx)

set(${CURRENT_TARGET}_pch ${TARGET_PUBLIC_PATH}/onyx.h)

set(TARGET_PUBLIC_SOURCES
	${TARGET_PUBLIC_PATH}/assert.h
	${TARGET_PUBLIC_PATH}/bitwiseenum.h
	${TARGET_PUBLIC_PATH}/defines.h
	${TARGET_PUBLIC_PATH}/encoding.h
	${TARGET_PUBLIC_PATH}/eventhandler.h
	${TARGET_PUBLIC_PATH}/guid.h
	${TARGET_PUBLIC_PATH}/hash.h
	${TARGET_PUBLIC_PATH}/inplacefunction.h
	${TARGET_PUBLIC_PATH}/math.h
	${TARGET_PUBLIC_PATH}/morton.h
	${TARGET_PUBLIC_PATH}/mortoncode2d.h
	${TARGET_PUBLIC_PATH}/mortoncode3d.h
	${TARGET_PUBLIC_PATH}/noncopyable.h
	${TARGET_PUBLIC_PATH}/onyx_core_common.h
	${TARGET_PUBLIC_PATH}/onyx_types.h
	${TARGET_PUBLIC_PATH}/onyx.h
	${TARGET_PUBLIC_PATH}/reference.h
	${TARGET_PUBLIC_PATH}/time.h
	${TARGET_PUBLIC_PATH}/typetraits.h
	${TARGET_PUBLIC_PATH}/container/arrayview.h
	${TARGET_PUBLIC_PATH}/container/directedacyclicgraph.h
	${TARGET_PUBLIC_PATH}/container/inplacearray.h
	${TARGET_PUBLIC_PATH}/container/memorybuffer.h
	${TARGET_PUBLIC_PATH}/container/staticarray.h
	${TARGET_PUBLIC_PATH}/container/span.h
	${TARGET_PUBLIC_PATH}/container/typelist.h
	${TARGET_PUBLIC_PATH}/engine/enginesystem.h
	${TARGET_PUBLIC_PATH}/function/callback.h
	${TARGET_PUBLIC_PATH}/function/signal.h
	${TARGET_PUBLIC_PATH}/geometry/common.h
	${TARGET_PUBLIC_PATH}/geometry/matrix2.h
	${TARGET_PUBLIC_PATH}/geometry/matrix3.h
	${TARGET_PUBLIC_PATH}/geometry/matrix4.h
	${TARGET_PUBLIC_PATH}/geometry/rotor3.h
	${TARGET_PUBLIC_PATH}/geometry/sat.h
	${TARGET_PUBLIC_PATH}/geometry/vector.h
	${TARGET_PUBLIC_PATH}/geometry/vector2.h
	${TARGET_PUBLIC_PATH}/geometry/vector3.h
	${TARGET_PUBLIC_PATH}/geometry/vector4.h
	${TARGET_PUBLIC_PATH}/log/backends/loggerbackend.h
	${TARGET_PUBLIC_PATH}/log/backends/stdoutlogger.h
	${TARGET_PUBLIC_PATH}/log/backends/visualstudiolog.h
	${TARGET_PUBLIC_PATH}/log/logger.h
	${TARGET_PUBLIC_PATH}/log/loglevel.h
	${TARGET_PUBLIC_PATH}/log/logmessage.h
	${TARGET_PUBLIC_PATH}/memory/objectpool.h
	${TARGET_PUBLIC_PATH}/platforms/platform.h
	${TARGET_PUBLIC_PATH}/platforms/windows/platform.h
	${TARGET_PUBLIC_PATH}/profiler/profiletimer.h
	${TARGET_PUBLIC_PATH}/stream/memorystream.h
	${TARGET_PUBLIC_PATH}/stream/stream.h
	${TARGET_PUBLIC_PATH}/stream/stringstream.h
	${TARGET_PUBLIC_PATH}/string/compiletimestring.h
	${TARGET_PUBLIC_PATH}/string/format.h
	${TARGET_PUBLIC_PATH}/string/inplacestring.h
	${TARGET_PUBLIC_PATH}/string/string.h
	${TARGET_PUBLIC_PATH}/thread/thread.h
	${TARGET_PUBLIC_PATH}/thread/async/asynctask.h
	${TARGET_PUBLIC_PATH}/thread/async/future.h
	${TARGET_PUBLIC_PATH}/thread/container/lockfreempmcboundedqueue.h
	${TARGET_PUBLIC_PATH}/thread/container/lockfreempmcboundedqueue.hpp
	${TARGET_PUBLIC_PATH}/thread/container/lockfreempscboundedqueue.h
	${TARGET_PUBLIC_PATH}/thread/container/lockfreempscboundedqueue.hpp
	${TARGET_PUBLIC_PATH}/thread/synchronization/atomic_latch.h
	${TARGET_PUBLIC_PATH}/thread/threadpool/threadpool.h
	${TARGET_PUBLIC_PATH}/thread/threadpool/threadpooloptions.h
	${TARGET_PUBLIC_PATH}/thread/threadpool/worker.h	
)

set(TARGET_PRIVATE_SOURCES		
	${TARGET_PRIVATE_PATH}/assert.cpp
	${TARGET_PRIVATE_PATH}/guid.cpp
	${TARGET_PRIVATE_PATH}/log/logger.cpp
	${TARGET_PRIVATE_PATH}/log/backends/stdoutlogger.cpp
	${TARGET_PRIVATE_PATH}/log/backends/visualstudiolog.cpp
	${TARGET_PRIVATE_PATH}/platforms/windows/platform.cpp
	${TARGET_PRIVATE_PATH}/stream/memorystream.cpp
	${TARGET_PRIVATE_PATH}/stream/stream.cpp
	${TARGET_PRIVATE_PATH}/stream/stringstream.cpp
	${TARGET_PRIVATE_PATH}/string/string.cpp
	${TARGET_PRIVATE_PATH}/thread/thread.cpp
)