set(onyx_TARGET_PCH onyx.h)

set(onyx_TARGET_PUBLIC_SOURCES
    assert.h
    bitwiseenum.h
    debugging.h
    defines.h
    encoding.h
    eventhandler.h
    guid.h
    hash.h
    inplacefunction.h
    math.h
    morton.h
    mortoncode2d.h
    mortoncode3d.h
    noncopyable.h
    onyx_core_common.h
    onyx_types.h
    onyx.h
    reference.h
    stringid.h
    time.h
    typetraits.h
    container/arrayview.h
    container/directedacyclicgraph.h
    container/inplacearray.h
    container/memorybuffer.h
    container/staticarray.h
    container/span.h
    container/typelist.h
    engine/enginesystem.h
    engine/enginesystemfactory.h
    engine/gametime.h
    function/callback.h
    function/signal.h
    geometry/common.h
    geometry/matrix2.h
    geometry/matrix3.h
    geometry/matrix4.h
    geometry/rect2.h
    geometry/rotor3.h
    geometry/sat.h
    geometry/vector.h
    geometry/vector2.h
    geometry/vector3.h
    geometry/vector4.h
    geometry/rectserialization.h
    geometry/vectorserialization.h
    log/backends/loggerbackend.h
    log/backends/stdoutlogger.h
    log/backends/visualstudiolog.h
    log/logger.h
    log/loglevel.h
    log/logmessage.h
    memory/objectpool.h
    platforms/platform.h
    platforms/windows/platform.h
    profiler/profiletimer.h
    serialize/serialization.h
    serialize/deserializer.h
    serialize/serializer.h
    stream/memorystream.h
    stream/stream.h
    stream/stringstream.h
    string/compiletimestring.h
    string/format.h
    string/inplacestring.h
    string/string.h
    thread/thread.h
    thread/async/asynctask.h
    thread/async/future.h
    thread/container/lockfreempmcboundedqueue.h
    thread/container/lockfreempmcboundedqueue.hpp
    thread/container/lockfreempscboundedqueue.h
    thread/container/lockfreempscboundedqueue.hpp
    thread/synchronization/atomic_latch.h
    thread/threadpool/threadpool.h
    thread/threadpool/threadpooloptions.h
    thread/threadpool/worker.h
    units/quantity.h
    units/ratio.h
    units/units.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    assert.cpp
    debugging.cpp
    guid.cpp
    hash.cpp
    stringid.cpp
    geometry/rectserialization.cpp
    geometry/vectorserialization.cpp
    log/logger.cpp
    log/backends/stdoutlogger.cpp
    log/backends/visualstudiolog.cpp
    platforms/windows/platform.cpp
    serialize/serialization.cpp
    stream/memorystream.cpp
    stream/stream.cpp
    stream/stringstream.cpp
    string/string.cpp
    thread/thread.cpp
)