set(onyx_TARGET_PUBLIC_SOURCES
    componentfactory.h
    componentmeta.h
    componentmeta.hpp
    entity.h
    entity.hpp
    ecsbuilder.h
    entitycomponentsystem.h
    entityregistry.h
    prefab.h
    prefabregistry.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    entitycomponentsystem.cpp
    componentfactory.cpp
    entityregistry.cpp
    prefabregistry.cpp
)