set(onyx_TARGET_PUBLIC_SOURCES
    executioncontext.h
    graph.h
    graphrunner.h
    nodegraphfactory.h
    nodegraphserializer.h
    nodegraphtypemeta.h
    nodegraphtyperegistry.h
    nodes/fixedpinnode1in.h
    nodes/fixedpinnode2in.h
    nodes/fixedpinnode1in1out.h
    nodes/fixedpinnode1in2out.h
    nodes/fixedpinnode1in3out.h
    nodes/fixedpinnode1in4out.h
    nodes/fixedpinnode1out.h
    nodes/fixedpinnode2in1out.h
    nodes/fixedpinnode2in2out.h
    nodes/fixedpinnode3in1out.h
    nodes/fixedpinnode4in1out.h
    nodes/fixedpinsnode.h
    nodes/flexiblepinsnode.h
    nodes/math/arithmeticnodes.h
    nodes/math/geometricnodes.h
    nodes/math/vectornodes_editor.h
    nodes/math/vectornodes.h
    nodes/node.h
    pins/dynamicpin.h
    pins/pin.h
    pins/pin.h
    pins/pinbase.h
    pins/pinmeta.h
    pins/pinmeta.hpp
)

set(onyx_TARGET_PRIVATE_SOURCES
    executioncontext.cpp
    graph.cpp
    graphrunner.cpp
    nodegraphfactory.cpp
    nodegraphserializer.cpp
    nodes/node.cpp
    pins/dynamicpin.cpp
)
