set(onyx_TARGET_PUBLIC_SOURCES
    gamecore.h
    components/cameracomponent.ocd
    components/freecameracomponent.ocd
    components/idcomponent.ocd
    components/namecomponent.ocd
    components/transformcomponent.h
    components/transformcomponent.ocd
    components/transientcomponent.ocd
    components/graphics/lightcomponents.h
    components/graphics/materialcomponent.h
    components/graphics/textcomponent.h
    rendertasks/depthprepassrendertask.h
    rendertasks/staticmeshrendertask.h
    rendertasks/textrendertask.h
    scene/sceneframedata.h
    scene/scene.h
    scene/scenesector.h
    scene/scenesectorstreamer.h
    serialize/sceneserializer.h
    systems/camerasystem.h
    systems/freecamerasystem.h
    systems/lightingsystem.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    gamecore.cpp
    components/transformcomponent.cpp
    components/graphics/lightcomponents.cpp
    components/graphics/materialcomponent.cpp
    components/graphics/textcomponent.cpp
    rendertasks/depthprepassrendertask.cpp
    rendertasks/staticmeshrendertask.cpp
    rendertasks/textrendertask.cpp
    scene/sceneframedata.cpp
    scene/scene.cpp
    scene/scenesectorstreamer.cpp
    serialize/sceneserializer.cpp
    systems/camerasystem.cpp
    systems/freecamerasystem.cpp
    systems/lightingsystem.cpp
)