set(onyx_TARGET_PUBLIC_SOURCES
    gamecore.h
    components/shapes/boxshapecomponent.ocd
    components/shapes/capsuleshapecomponent.ocd
    components/shapes/sphereshapecomponent.ocd
    components/graphics/directionallightcomponent.ocd
    components/graphics/materialcomponent.ocd
    components/graphics/pointlightcomponent.ocd
    components/graphics/spotlightcomponent.ocd
    components/graphics/staticmeshcomponent.ocd
    components/graphics/textcomponent.ocd
    components/physics/characterbodycomponent.ocd
    components/physics/kinematicbodycomponent.ocd
    components/physics/rigidbodycomponent.ocd
    components/physics/staticbodycomponent.ocd
    components/cameracomponent.ocd
    components/freecameracomponent.ocd
    components/idcomponent.ocd
    components/namecomponent.ocd
    components/transformcomponent.h
    components/transformcomponent.ocd
    components/transientcomponent.ocd
    rendertasks/depthprepassrendertask.h
    rendertasks/staticmeshrendertask.h
    rendertasks/textrendertask.h
    scene/sceneframedata.h
    scene/scene.h
    scene/scenesector.h
    scene/scenesectorstreamer.h
    serialize/sceneserializer.h
    systems/charactersystem.h
    systems/camerasystem.h
    systems/freecamerasystem.h
    systems/lightingsystem.h
    systems/movementsystem.h
    systems/physicssystem.h
    systems/staticmeshentitysystem.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    gamecore.cpp
    components/transformcomponent.cpp
    rendertasks/depthprepassrendertask.cpp
    rendertasks/staticmeshrendertask.cpp
    rendertasks/textrendertask.cpp
    scene/sceneframedata.cpp
    scene/scene.cpp
    scene/scenesectorstreamer.cpp
    serialize/sceneserializer.cpp
    systems/charactersystem.cpp
    systems/camerasystem.cpp
    systems/freecamerasystem.cpp
    systems/lightingsystem.cpp
    systems/movementsystem.cpp
    systems/physicssystem.cpp
    systems/staticmeshentitysystem.cpp
)
