set(onyx_TARGET_PUBLIC_SOURCES
    localization.h
    localizationbackend.h
    localizationmodule.h
    localizedstring.h
    assets/localizationdatabase.h
    assets/gettextlocalizationdatabase.h
    backends/gettextlocalizationbackend.h
    serialize/portableobjectserializer.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    localization.cpp
    localizationbackend.cpp
    localizationmodule.cpp
    localizedstring.cpp
    backends/gettextlocalizationbackend.cpp
    serialize/portableobjectserializer.cpp
)