set(onyx_TARGET_PUBLIC_SOURCES
    asset.h
    assetformat.h
    assethandle.h
    assethotreloadsystem.h
    assetid.h
    assetloader.h
    assetloadrequest.h
    assetserializer.h
    assetsystem.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    assethotreloadsystem.cpp
    assetid.cpp
    assetloader.cpp
    assetloadrequest.cpp
    assetsystem.cpp
)
