set(TARGET_PUBLIC_PATH ${CMAKE_CURRENT_SOURCE_DIR}/public/onyx/input)
set(TARGET_PRIVATE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/private/onyx/input)

set(TARGET_PUBLIC_SOURCES
    ${TARGET_PUBLIC_PATH}/gamecontroller.h
    ${TARGET_PUBLIC_PATH}/inputaction.h
    ${TARGET_PUBLIC_PATH}/inputactionsasset.h
    ${TARGET_PUBLIC_PATH}/inputactionsmap.h
    ${TARGET_PUBLIC_PATH}/inputactionsserializer.h
    ${TARGET_PUBLIC_PATH}/inputactionsystem.h
    ${TARGET_PUBLIC_PATH}/inputid.h
    ${TARGET_PUBLIC_PATH}/inputsystem.h
    ${TARGET_PUBLIC_PATH}/inputtypes.h
    ${TARGET_PUBLIC_PATH}/keycodes.h
    ${TARGET_PUBLIC_PATH}/mouse.h
    ${TARGET_PUBLIC_PATH}/bindings/inputbinding.h
    ${TARGET_PUBLIC_PATH}/bindings/inputbindingaxis1d.h
    ${TARGET_PUBLIC_PATH}/bindings/inputbindingaxis1dcomposite.h
    ${TARGET_PUBLIC_PATH}/bindings/inputbindingaxis2d.h
    ${TARGET_PUBLIC_PATH}/bindings/inputbindingaxis2dcomposite.h
    ${TARGET_PUBLIC_PATH}/bindings/inputbindingaxis3d.h
    ${TARGET_PUBLIC_PATH}/bindings/inputbindingaxis3dcomposite.h
    ${TARGET_PUBLIC_PATH}/bindings/inputbindingbool.h
    ${TARGET_PUBLIC_PATH}/bindings/inputbindingsfactory.h
    ${TARGET_PUBLIC_PATH}/modifiers/inputmodifier.h
    ${TARGET_PUBLIC_PATH}/modifiers/inputmodifiersfactory.h
    ${TARGET_PUBLIC_PATH}/triggers/inputtrigger.h
    ${TARGET_PUBLIC_PATH}/triggers/inputtriggersfactory.h
    ${TARGET_PUBLIC_PATH}/platform/windows/windows_gamecontroller.h
    ${TARGET_PUBLIC_PATH}/platform/windows/windows_keycodes.h
    ${TARGET_PUBLIC_PATH}/triggers/dependantactiontrigger.h
)

set(TARGET_PRIVATE_SOURCES
    ${TARGET_PRIVATE_PATH}/inputaction.cpp
    ${TARGET_PRIVATE_PATH}/inputactionsasset.cpp
    ${TARGET_PRIVATE_PATH}/inputactionsmap.cpp
    ${TARGET_PRIVATE_PATH}/inputactionsserializer.cpp
    ${TARGET_PRIVATE_PATH}/inputactionsystem.cpp
    ${TARGET_PRIVATE_PATH}/inputid.cpp
    ${TARGET_PRIVATE_PATH}/inputsystem.cpp
    ${TARGET_PRIVATE_PATH}/bindings/inputbinding.cpp
    ${TARGET_PRIVATE_PATH}/bindings/inputbindingaxis1d.cpp
    ${TARGET_PRIVATE_PATH}/bindings/inputbindingaxis1dcomposite.cpp
    ${TARGET_PRIVATE_PATH}/bindings/inputbindingaxis2d.cpp
    ${TARGET_PRIVATE_PATH}/bindings/inputbindingaxis2dcomposite.cpp
    ${TARGET_PRIVATE_PATH}/bindings/inputbindingaxis3d.cpp
    ${TARGET_PRIVATE_PATH}/bindings/inputbindingaxis3dcomposite.cpp
    ${TARGET_PRIVATE_PATH}/bindings/inputbindingbool.cpp
    ${TARGET_PRIVATE_PATH}/bindings/inputbindingsfactory.cpp
    ${TARGET_PRIVATE_PATH}/modifiers/inputmodifier.cpp
    ${TARGET_PRIVATE_PATH}/modifiers/inputmodifiersfactory.cpp
    ${TARGET_PRIVATE_PATH}/platform/windows/windows_gamecontroller.cpp
    ${TARGET_PRIVATE_PATH}/triggers/dependantactiontrigger.cpp
    ${TARGET_PRIVATE_PATH}/triggers/inputtrigger.cpp
    ${TARGET_PRIVATE_PATH}/triggers/inputtriggersfactory.cpp
)