set(onyx_TARGET_PUBLIC_SOURCES
    editormodule.h
    editor_localization.h
    camera/freecamera.h
    assets/importer/assetimporter.h
    assets/importer/textureimporter.h
    nodegraph/grapheditorcontext.h
    nodegraph/nodegrapheditorcontext.h
    nodegraph/rendergrapheditorcontext.h
    nodegraph/shadergrapheditorcontext.h
    nodegraph/typenodegrapheditorcontext.h
    nodegraph/volumeshadergrapheditorcontext.h
    modules/nodeeditor.h
    modules/sceneeditor.h
    panels/contentbrowserpanel.h
    panels/nodeeditor/canvaspanel.h
    panels/nodeeditor/propertiespanel.h
    panels/nodeeditor/styles/blueprint.h
    panels/nodeeditor/styles/drawing.h
    panels/nodeeditor/styles/widgets.h
    panels/sceneeditor/entitiespanel.h
    panels/sceneeditor/componentspanel.h
    panels/sceneeditor/terrainpanel.h
    panels/sceneeditor/terraintools/terraintool.h
    panels/sceneeditor/terraintools/sculptterraintool.h
    panels/sceneeditor/terraintools/primitivesterraintool.h
    rendertasks/compositetask.h
    rendertasks/gridtask.h
    windows/editorwindow.h
    windows/editormainwindow.h
    windows/startupwindow.h
    windows/settings/inputactionsettingswindow.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    editormodule.cpp
    editor_localization.cpp
    camera/freecamera.cpp
    assets/importer/textureimporter.cpp
    components/graphics/lightcomponents.cpp
    components/graphics/materialcomponent.cpp
    components/graphics/textcomponent_editor.cpp
    components/volume/csg/spherecomponent_editor.cpp
    components/volume/volumeterraincomponent_editor.cpp
    nodegraph/arithmeticnodes_editor.cpp
    nodegraph/vectornodes_editor.cpp
    nodegraph/grapheditorcontext.cpp
    nodegraph/nodegrapheditorcontext.cpp
    nodegraph/pin.cpp
    nodegraph/rendergrapheditorcontext.cpp
    nodegraph/rendergraphnodes_editor.cpp
    nodegraph/shadergrapheditorcontext.cpp
    nodegraph/volumeshadergrapheditorcontext.cpp
    modules/nodeeditor.cpp
    modules/sceneeditor.cpp
    panels/contentbrowserpanel.cpp
    panels/nodeeditor/canvaspanel.cpp
    panels/nodeeditor/propertiespanel.cpp
    panels/nodeeditor/styles/blueprint.cpp
    panels/nodeeditor/styles/drawing.cpp
    panels/nodeeditor/styles/widgets.cpp
    panels/sceneeditor/entitiespanel.cpp
    panels/sceneeditor/componentspanel.cpp
    panels/sceneeditor/terrainpanel.cpp
    panels/sceneeditor/terraintools/terraintool.cpp
    panels/sceneeditor/terraintools/sculptterraintool.cpp
    panels/sceneeditor/terraintools/primitivesterraintool.cpp
    rendertasks/compositetask.cpp
    rendertasks/gridtask.cpp
    shadergraph/sampletexturenode_editor.cpp
    windows/editorwindow.cpp
    windows/editormainwindow.cpp
    windows/startupwindow.cpp
    windows/settings/inputactionsettingswindow.cpp
)