set(onyx_TARGET_PUBLIC_SOURCES
    editormodule.h
    editor_localization.h
    camera/freecamera.h
    commands/command.h
    commands/commandgraph.h
    commands/inputactions/addinputactioncommand.h
    commands/inputactions/addinputbindingcommand.h
    commands/inputactions/addinputmodifiercommand.h
    commands/inputactions/addinputtriggercommand.h
    commands/inputactions/bindinputbindingslotcommand.h
    commands/inputactions/deleteinputactioncommand.h
    commands/inputactions/deleteinputbindingcommand.h
    commands/inputactions/deleteinputmodifiercommand.h
    commands/inputactions/deleteinputtriggercommand.h
    commands/inputactions/inputactioncommand.h
    commands/inputactions/modifyinputactioncommand.h
    commands/inputactions/renameinputactioncommand.h
    commands/scene/addcomponentcommand.h
    commands/scene/createentitycommand.h
    commands/scene/deleteentitycommand.h
    commands/scene/modifycomponentcommand.h
    commands/scene/renameentitycommand.h
    commands/scene/scenecommand.h
    assets/importer/assetimporter.h
    assets/importer/textureimporter.h
    nodegraph/grapheditorcontext.h
    nodegraph/nodegrapheditorcontext.h
    nodegraph/rendergrapheditorcontext.h
    nodegraph/shadergrapheditorcontext.h
    nodegraph/typenodegrapheditorcontext.h
    nodegraph/volumeshadergrapheditorcontext.h
    panels/contentbrowserpanel.h
    panels/nodeeditor/canvaspanel.h
    panels/nodeeditor/propertiespanel.h
    panels/nodeeditor/styles/blueprint.h
    panels/nodeeditor/styles/drawing.h
    panels/nodeeditor/styles/widgets.h
    panels/sceneeditor/entitiespanel.h
    panels/sceneeditor/componentspanel.h
    panels/sceneeditor/terrainpanel.h
    panels/sceneeditor/terraintools/terraintool.h
    panels/sceneeditor/terraintools/sculptterraintool.h
    panels/sceneeditor/terraintools/primitivesterraintool.h
    rendertasks/compositetask.h
    rendertasks/gridtask.h
    windows/commandhistorywindow.h
    windows/editorwindow.h
    windows/editormainwindow.h
    windows/nodegrapheditor.h
    windows/sceneeditor.h
    windows/sceneviewport.h
    windows/startupwindow.h
    windows/settings/camerasettingswindow.h
    windows/settings/gridsettingswindow.h
    windows/settings/inputactionsettingswindow.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    editormodule.cpp
    editor_localization.cpp
    camera/freecamera.cpp
    commands/inputactions/addinputactioncommand.cpp
    commands/inputactions/addinputbindingcommand.cpp
    commands/inputactions/addinputmodifiercommand.cpp
    commands/inputactions/addinputtriggercommand.cpp
    commands/inputactions/bindinputbindingslotcommand.cpp
    commands/inputactions/deleteinputactioncommand.cpp
    commands/inputactions/deleteinputbindingcommand.cpp
    commands/inputactions/deleteinputmodifiercommand.cpp
    commands/inputactions/deleteinputtriggercommand.cpp
    commands/inputactions/inputactioncommand.cpp
    commands/inputactions/modifyinputactioncommand.cpp
    commands/inputactions/renameinputactioncommand.cpp
    commands/scene/addcomponentcommand.cpp
    commands/scene/createentitycommand.cpp
    commands/scene/deleteentitycommand.cpp
    commands/scene/modifycomponentcommand.cpp
    commands/scene/renameentitycommand.cpp
    commands/scene/scenecommand.cpp
    assets/importer/textureimporter.cpp
    nodegraph/arithmeticnodes_editor.cpp
    nodegraph/vectornodes_editor.cpp
    nodegraph/grapheditorcontext.cpp
    nodegraph/nodegrapheditorcontext.cpp
    nodegraph/pin.cpp
    nodegraph/rendergrapheditorcontext.cpp
    nodegraph/rendergraphnodes_editor.cpp
    nodegraph/shadergrapheditorcontext.cpp
    nodegraph/volumeshadergrapheditorcontext.cpp
    panels/contentbrowserpanel.cpp
    panels/nodeeditor/canvaspanel.cpp
    panels/nodeeditor/propertiespanel.cpp
    panels/nodeeditor/styles/blueprint.cpp
    panels/nodeeditor/styles/drawing.cpp
    panels/nodeeditor/styles/widgets.cpp
    panels/sceneeditor/entitiespanel.cpp
    panels/sceneeditor/componentspanel.cpp
    panels/sceneeditor/terrainpanel.cpp
    panels/sceneeditor/terraintools/terraintool.cpp
    panels/sceneeditor/terraintools/sculptterraintool.cpp
    panels/sceneeditor/terraintools/primitivesterraintool.cpp
    rendertasks/compositetask.cpp
    rendertasks/gridtask.cpp
    shadergraph/sampletexturenode_editor.cpp
    windows/commandhistorywindow.cpp
    windows/editorwindow.cpp
    windows/editormainwindow.cpp
    windows/nodegrapheditor.cpp
    windows/sceneeditor.cpp
    windows/sceneviewport.cpp
    windows/startupwindow.cpp
    windows/settings/camerasettingswindow.cpp
    windows/settings/gridsettingswindow.cpp
    windows/settings/inputactionsettingswindow.cpp
)