set(TARGET_PUBLIC_PATH ${CMAKE_CURRENT_SOURCE_DIR}/public/onyx/volume)
set(TARGET_PRIVATE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/private/onyx/volume)

set(TARGET_PUBLIC_SOURCES
    ${TARGET_PUBLIC_PATH}/chunk/cms_volumechunk.h
    ${TARGET_PUBLIC_PATH}/chunk/volumechunk.h
    ${TARGET_PUBLIC_PATH}/chunk/volumechunkloader.h
    ${TARGET_PUBLIC_PATH}/chunk/volumechunkloadrequest.h
    ${TARGET_PUBLIC_PATH}/components/volumesourcerenderdatacomponent.h
    ${TARGET_PUBLIC_PATH}/components/volumeterraincomponent.h
    ${TARGET_PUBLIC_PATH}/components/csg/cubecomponent.h
    ${TARGET_PUBLIC_PATH}/components/csg/planecomponent.h
    ${TARGET_PUBLIC_PATH}/components/csg/spherecomponent.h
    ${TARGET_PUBLIC_PATH}/cubicalmarchingsquares/cmsoctreesplitpolicy.h
    ${TARGET_PUBLIC_PATH}/cubicalmarchingsquares/linesegment.h
    ${TARGET_PUBLIC_PATH}/cubicalmarchingsquares/vertex.h
    ${TARGET_PUBLIC_PATH}/dualgrid/dualgrid.h
    ${TARGET_PUBLIC_PATH}/dualgrid/dualgrid.hpp
    ${TARGET_PUBLIC_PATH}/dualmarchingcubes/dmcoctreesplitpolicy.h
    ${TARGET_PUBLIC_PATH}/graphics/previewterrainedit.h
    ${TARGET_PUBLIC_PATH}/isosurface/isosurface.h
    ${TARGET_PUBLIC_PATH}/isosurface/marchingcubessurface.h
    ${TARGET_PUBLIC_PATH}/isosurface/marchingcubestable.h
    ${TARGET_PUBLIC_PATH}/isosurface/marchingsquaressurface_cms.h
    ${TARGET_PUBLIC_PATH}/isosurface/marchingsquaressurface.h
    ${TARGET_PUBLIC_PATH}/isosurface/marchingsquarestable_cms.h
    ${TARGET_PUBLIC_PATH}/isosurface/marchingsquarestable.h
    ${TARGET_PUBLIC_PATH}/mesh/meshbuilder.h
    ${TARGET_PUBLIC_PATH}/octree/octree.h
    ${TARGET_PUBLIC_PATH}/octree/octree.hpp
    ${TARGET_PUBLIC_PATH}/octree/octreebreadthfirstiterator.h
    ${TARGET_PUBLIC_PATH}/octree/octreebreadthfirstiterator.hpp
    ${TARGET_PUBLIC_PATH}/octree/octreedepthfirstiterator.h
    ${TARGET_PUBLIC_PATH}/octree/octreedepthfirstiterator.hpp
    ${TARGET_PUBLIC_PATH}/octree/octreeiteratorbase.h
    ${TARGET_PUBLIC_PATH}/octree/octreekey.h
    ${TARGET_PUBLIC_PATH}/octree/octreeleafnodeiterator.h
    ${TARGET_PUBLIC_PATH}/octree/octreenode.h
    ${TARGET_PUBLIC_PATH}/octree/octreenode.hpp
    ${TARGET_PUBLIC_PATH}/octree/octreesearch.h
    ${TARGET_PUBLIC_PATH}/octree/octreesplitpolicy.h
    ${TARGET_PUBLIC_PATH}/onyx_export.h
    ${TARGET_PUBLIC_PATH}/onyx_volume_pch.h
    ${TARGET_PUBLIC_PATH}/onyxunrealcoordinatetransforms.h
    ${TARGET_PUBLIC_PATH}/onyxunrealutil.h
    ${TARGET_PUBLIC_PATH}/shader/generators/volumeshadergraphgenerator.h
    ${TARGET_PUBLIC_PATH}/shadergraph/volumeshadergraph.h
    ${TARGET_PUBLIC_PATH}/shadergraph/nodes/operations/differencevolumeshadergraphnode.h
    ${TARGET_PUBLIC_PATH}/shadergraph/nodes/operations/intersectvolumeshadergraphnode.h
    ${TARGET_PUBLIC_PATH}/shadergraph/nodes/operations/unionvolumeshadergraphnode.h
    ${TARGET_PUBLIC_PATH}/shadergraph/nodes/primitives/planevolumeshadergraphnode.h
    ${TARGET_PUBLIC_PATH}/shadergraph/nodes/primitives/cubevolumeshadergraphnode.h
    ${TARGET_PUBLIC_PATH}/shadergraph/nodes/primitives/ellipsoidvolumeshadergraphnode.h
    ${TARGET_PUBLIC_PATH}/shadergraph/nodes/primitives/spherevolumeshadergraphnode.h
    ${TARGET_PUBLIC_PATH}/shadergraph/nodes/primitives/planevolumeshadergraphnode.h
    ${TARGET_PUBLIC_PATH}/shadergraph/nodes/volumeshadergraphoutnode.h
    ${TARGET_PUBLIC_PATH}/serialize/volumeshadergraphserializer.h
    ${TARGET_PUBLIC_PATH}/source/csg/csgcube.h
    ${TARGET_PUBLIC_PATH}/source/csg/csgplane.h
    ${TARGET_PUBLIC_PATH}/source/csg/csgsphere.h
    ${TARGET_PUBLIC_PATH}/source/csg/operations/csgdifference.h
    ${TARGET_PUBLIC_PATH}/source/csg/operations/csgintersect.h
    ${TARGET_PUBLIC_PATH}/source/csg/operations/csgnegate.h
    ${TARGET_PUBLIC_PATH}/source/csg/operations/csgoperation.h
    ${TARGET_PUBLIC_PATH}/source/csg/operations/csgscale.h
    ${TARGET_PUBLIC_PATH}/source/csg/operations/csgunary.h
    ${TARGET_PUBLIC_PATH}/source/csg/operations/csgunion.h
    ${TARGET_PUBLIC_PATH}/source/csgsource.h
    ${TARGET_PUBLIC_PATH}/source/noise/simplexnoised.h
    ${TARGET_PUBLIC_PATH}/source/noise/simplexnoisesource.h
    ${TARGET_PUBLIC_PATH}/source/volumebase.h
    ${TARGET_PUBLIC_PATH}/systems/volumeterrainsystem.h
    ${TARGET_PUBLIC_PATH}/systems/volumerendersystem.h
    ${TARGET_PUBLIC_PATH}/terrain/worldsparseoctreenode.h
    ${TARGET_PUBLIC_PATH}/tree/tree.h
    ${TARGET_PUBLIC_PATH}/tree/tree.hpp
    ${TARGET_PUBLIC_PATH}/tree/treebreadthfirstiterator.h
    ${TARGET_PUBLIC_PATH}/tree/treebreadthfirstiterator.hpp
    ${TARGET_PUBLIC_PATH}/tree/treedepthfirstiterator.h
    ${TARGET_PUBLIC_PATH}/tree/treedepthfirstiterator.hpp
    ${TARGET_PUBLIC_PATH}/tree/treeiterator.h
    ${TARGET_PUBLIC_PATH}/tree/treeleafiterator.h
    ${TARGET_PUBLIC_PATH}/tree/treenode.h
    ${TARGET_PUBLIC_PATH}/volumemodule.h
    ${TARGET_PUBLIC_PATH}/volumeterrain.h
)

set(TARGET_PRIVATE_SOURCES
    ${TARGET_PRIVATE_PATH}/chunk/cms_volumechunk.cpp
    ${TARGET_PRIVATE_PATH}/chunk/volumechunk.cpp
    ${TARGET_PRIVATE_PATH}/chunk/volumechunkloader.cpp
    ${TARGET_PRIVATE_PATH}/chunk/volumechunkloadrequest.cpp
    ${TARGET_PRIVATE_PATH}/components/volumeterraincomponent.cpp
    ${TARGET_PRIVATE_PATH}/components/csg/cubecomponent.cpp
    ${TARGET_PRIVATE_PATH}/components/csg/planecomponent.cpp
    ${TARGET_PRIVATE_PATH}/components/csg/spherecomponent.cpp
    ${TARGET_PRIVATE_PATH}/graphics/previewterrainedit.cpp
    ${TARGET_PRIVATE_PATH}/isosurface/isosurface.cpp
    ${TARGET_PRIVATE_PATH}/isosurface/marchingcubessurface.cpp
    ${TARGET_PRIVATE_PATH}/isosurface/marchingsquaressurface.cpp
    ${TARGET_PRIVATE_PATH}/shader/generators/volumeshadergraphgenerator.cpp
    ${TARGET_PRIVATE_PATH}/shadergraph/nodes/operations/differencevolumeshadergraphnode.cpp
    ${TARGET_PRIVATE_PATH}/shadergraph/nodes/operations/intersectvolumeshadergraphnode.cpp
    ${TARGET_PRIVATE_PATH}/shadergraph/nodes/operations/unionvolumeshadergraphnode.cpp
    ${TARGET_PRIVATE_PATH}/shadergraph/nodes/primitives/cubevolumeshadergraphnode.cpp
    ${TARGET_PRIVATE_PATH}/shadergraph/nodes/primitives/ellipsoidvolumeshadergraphnode.cpp
    ${TARGET_PRIVATE_PATH}/shadergraph/nodes/primitives/spherevolumeshadergraphnode.cpp
    ${TARGET_PRIVATE_PATH}/shadergraph/nodes/primitives/planevolumeshadergraphnode.cpp
    ${TARGET_PRIVATE_PATH}/shadergraph/nodes/volumeshadergraphoutnode.cpp
    ${TARGET_PRIVATE_PATH}/serialize/volumeshadergraphserializer.cpp
    ${TARGET_PRIVATE_PATH}/source/csg/csgsphere.cpp
    ${TARGET_PRIVATE_PATH}/source/csg/operations/csgdifference.cpp
    ${TARGET_PRIVATE_PATH}/source/csg/operations/csgintersect.cpp
    ${TARGET_PRIVATE_PATH}/source/csg/operations/csgnegate.cpp
    ${TARGET_PRIVATE_PATH}/source/csg/operations/csgscale.cpp
    ${TARGET_PRIVATE_PATH}/source/csg/operations/csgunion.cpp
    ${TARGET_PRIVATE_PATH}/source/noise/simplexnoised.cpp
    ${TARGET_PRIVATE_PATH}/source/volumebase.cpp
    ${TARGET_PRIVATE_PATH}/systems/volumeterrainsystem.cpp
    ${TARGET_PRIVATE_PATH}/systems/volumerendersystem.cpp
    ${TARGET_PRIVATE_PATH}/volumeterrain.cpp
    ${TARGET_PRIVATE_PATH}/volumemodule.cpp
)