set(onyx_TARGET_PUBLIC_SOURCES
    chunk/cms_volumechunk.h
    chunk/volumechunk.h
    chunk/volumechunkloader.h
    chunk/volumechunkloadrequest.h
    components/volumesourcerenderdatacomponent.h
    components/volumeterraincomponent.h
    components/csg/cubecomponent.h
    components/csg/planecomponent.h
    components/csg/spherecomponent.h
    cubicalmarchingsquares/cmsoctreesplitpolicy.h
    cubicalmarchingsquares/linesegment.h
    cubicalmarchingsquares/vertex.h
    dualgrid/dualgrid.h
    dualgrid/dualgrid.hpp
    dualmarchingcubes/dmcoctreesplitpolicy.h
    graphics/previewterrainedit.h
    isosurface/isosurface.h
    isosurface/marchingcubessurface.h
    isosurface/marchingcubestable.h
    isosurface/marchingsquaressurface_cms.h
    isosurface/marchingsquaressurface.h
    isosurface/marchingsquarestable_cms.h
    isosurface/marchingsquarestable.h
    mesh/meshbuilder.h
    octree/metadata.h
    octree/octree.h
    octree/octree.hpp
    octree/octreebreadthfirstiterator.h
    octree/octreebreadthfirstiterator.hpp
    octree/octreedepthfirstiterator.h
    octree/octreedepthfirstiterator.hpp
    octree/octreeiteratorbase.h
    octree/octreekey.h
    octree/octreeleafnodeiterator.h
    octree/octreenode.h
    octree/octreenode.hpp
    octree/octreesearch.h
    octree/octreesplitpolicy.h
    shader/generators/volumeshadergraphgenerator.h
    shader/generators/templates/volumeshadertemplates.h
    shadergraph/volumeshadergraph.h
    shadergraph/nodes/operations/sdfdifferencevolumeshadergraphnode.h
    shadergraph/nodes/operations/sdfintersectvolumeshadergraphnode.h
    shadergraph/nodes/operations/sdfunionvolumeshadergraphnode.h
    shadergraph/nodes/primitives/sdfplanevolumeshadergraphnode.h
    shadergraph/nodes/primitives/sdfcubevolumeshadergraphnode.h
    shadergraph/nodes/primitives/sdfellipsoidvolumeshadergraphnode.h
    shadergraph/nodes/primitives/sdfspherevolumeshadergraphnode.h
    shadergraph/nodes/primitives/sdfplanevolumeshadergraphnode.h
    shadergraph/nodes/sdfnoiseshadergraphnode.h
    shadergraph/nodes/volumeshadergraphoutnode.h
    shadergraph/nodes/voxelpositionshadergraphnode.h
    serialize/volumeshadergraphserializer.h
    source/csg/csgcube.h
    source/csg/csgplane.h
    source/csg/csgsphere.h
    source/csg/operations/csgdifference.h
    source/csg/operations/csgintersect.h
    source/csg/operations/csgnegate.h
    source/csg/operations/csgoperation.h
    source/csg/operations/csgscale.h
    source/csg/operations/csgunary.h
    source/csg/operations/csgunion.h
    source/csgsource.h
    source/noise/simplexnoised.h
    source/noise/simplexnoisesource.h
    source/volumebase.h
    systems/volumeterrainsystem.h
    systems/volumerendersystem.h
    terrain/worldsparseoctreenode.h
    tree/tree.h
    tree/tree.hpp
    tree/treebreadthfirstiterator.h
    tree/treebreadthfirstiterator.hpp
    tree/treedepthfirstiterator.h
    tree/treedepthfirstiterator.hpp
    tree/treeiterator.h
    tree/treeleafiterator.h
    tree/treenode.h
    volumemodule.h
    volumeterrain.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    chunk/cms_volumechunk.cpp
    chunk/volumechunk.cpp
    chunk/volumechunkloader.cpp
    chunk/volumechunkloadrequest.cpp
    components/volumeterraincomponent.cpp
    components/csg/cubecomponent.cpp
    components/csg/planecomponent.cpp
    components/csg/spherecomponent.cpp
    graphics/previewterrainedit.cpp
    isosurface/isosurface.cpp
    isosurface/marchingcubessurface.cpp
    isosurface/marchingsquaressurface.cpp
    shader/generators/volumeshadergraphgenerator.cpp
    shadergraph/nodes/operations/sdfdifferencevolumeshadergraphnode.cpp
    shadergraph/nodes/operations/sdfintersectvolumeshadergraphnode.cpp
    shadergraph/nodes/operations/sdfunionvolumeshadergraphnode.cpp
    shadergraph/nodes/primitives/sdfcubevolumeshadergraphnode.cpp
    shadergraph/nodes/primitives/sdfellipsoidvolumeshadergraphnode.cpp
    shadergraph/nodes/primitives/sdfspherevolumeshadergraphnode.cpp
    shadergraph/nodes/primitives/sdfplanevolumeshadergraphnode.cpp
    shadergraph/nodes/sdfnoiseshadergraphnode.cpp
    shadergraph/nodes/volumeshadergraphoutnode.cpp
    shadergraph/nodes/voxelpositionshadergraphnode.cpp
    serialize/volumeshadergraphserializer.cpp
    source/csg/csgsphere.cpp
    source/csg/operations/csgdifference.cpp
    source/csg/operations/csgintersect.cpp
    source/csg/operations/csgnegate.cpp
    source/csg/operations/csgscale.cpp
    source/csg/operations/csgunion.cpp
    source/noise/simplexnoised.cpp
    source/volumebase.cpp
    systems/volumeterrainsystem.cpp
    systems/volumerendersystem.cpp
    volumeterrain.cpp
    volumemodule.cpp
)