set(TARGET_PUBLIC_PATH ${CMAKE_CURRENT_SOURCE_DIR}/public/onyx/volume)
set(TARGET_PRIVATE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/private/onyx/volume)


set(TARGET_PUBLIC_SOURCES
    ${TARGET_PUBLIC_PATH}/volumesystem.h
	${TARGET_PUBLIC_PATH}/dualgrid/dualgrid.h
	${TARGET_PUBLIC_PATH}/dualgrid/dualgrid.hpp
	${TARGET_PUBLIC_PATH}/octree/octree.h
	${TARGET_PUBLIC_PATH}/octree/octree.hpp
	${TARGET_PUBLIC_PATH}/octree/octreebreadthfirstiterator.h
	${TARGET_PUBLIC_PATH}/octree/octreebreadthfirstiterator.hpp
	${TARGET_PUBLIC_PATH}/octree/octreedepthfirstiterator.h
	${TARGET_PUBLIC_PATH}/octree/octreedepthfirstiterator.hpp
	${TARGET_PUBLIC_PATH}/octree/octreekey.h
	${TARGET_PUBLIC_PATH}/octree/octreeleafnodeiterator.h
	${TARGET_PUBLIC_PATH}/octree/octreenode.h
	${TARGET_PUBLIC_PATH}/octree/octreenode.hpp
	${TARGET_PUBLIC_PATH}/octree/octreesearch.h
	${TARGET_PUBLIC_PATH}/octree/octreesplitpolicy.h
	${TARGET_PUBLIC_PATH}/octree/octreeiteratorbase.h
	${TARGET_PUBLIC_PATH}/chunk/cms_volumechunk.h
	${TARGET_PUBLIC_PATH}/chunk/volumechunk.h
	${TARGET_PUBLIC_PATH}/chunk/volumechunkloadrequest.h
	${TARGET_PUBLIC_PATH}/chunk/volumechunkloader.h
	${TARGET_PUBLIC_PATH}/components/volumecomponent.h
	${TARGET_PUBLIC_PATH}/isosurface/isosurface.h
	${TARGET_PUBLIC_PATH}/isosurface/marchingcubessurface.h
	${TARGET_PUBLIC_PATH}/isosurface/marchingcubestable.h
	${TARGET_PUBLIC_PATH}/isosurface/marchingsquaressurface.h
	${TARGET_PUBLIC_PATH}/isosurface/marchingsquaressurface_cms.h
	${TARGET_PUBLIC_PATH}/isosurface/marchingsquarestable.h
	${TARGET_PUBLIC_PATH}/isosurface/marchingsquarestable_cms.h
	${TARGET_PUBLIC_PATH}/source/csg/csgcube.h
	${TARGET_PUBLIC_PATH}/source/csg/csgplane.h
	${TARGET_PUBLIC_PATH}/source/csg/csgsphere.h
	${TARGET_PUBLIC_PATH}/source/csg/operations/csgdifference.h
	${TARGET_PUBLIC_PATH}/source/csg/operations/csgintersect.h
	${TARGET_PUBLIC_PATH}/source/csg/operations/csgnegate.h
	${TARGET_PUBLIC_PATH}/source/csg/operations/csgoperation.h
	${TARGET_PUBLIC_PATH}/source/csg/operations/csgscale.h
	${TARGET_PUBLIC_PATH}/source/csg/operations/csgunary.h
	${TARGET_PUBLIC_PATH}/source/csg/operations/csgunion.h
	${TARGET_PUBLIC_PATH}/source/csgsource.h
	${TARGET_PUBLIC_PATH}/source/noise/simplexnoised.h
	${TARGET_PUBLIC_PATH}/source/noise/simplexnoisesource.h
	${TARGET_PUBLIC_PATH}/source/volumebase.h
	${TARGET_PUBLIC_PATH}/volumeterrain.h
	${TARGET_PUBLIC_PATH}/cubicalmarchingsquares/cmsoctreesplitpolicy.h
	${TARGET_PUBLIC_PATH}/cubicalmarchingsquares/linesegment.h
	${TARGET_PUBLIC_PATH}/cubicalmarchingsquares/vertex.h
	${TARGET_PUBLIC_PATH}/dualmarchingcubes/dmcoctreesplitpolicy.h
	${TARGET_PUBLIC_PATH}/mesh/meshbuilder.h
	${TARGET_PUBLIC_PATH}/onyx_volume_pch.h
	${TARGET_PUBLIC_PATH}/onyx_export.h
	${TARGET_PUBLIC_PATH}/onyxunrealcoordinatetransforms.h
	${TARGET_PUBLIC_PATH}/onyxunrealutil.h
	${TARGET_PUBLIC_PATH}/tree/tree.h
	${TARGET_PUBLIC_PATH}/tree/tree.hpp
	${TARGET_PUBLIC_PATH}/tree/treebreadthfirstiterator.h
	${TARGET_PUBLIC_PATH}/tree/treebreadthfirstiterator.hpp
	${TARGET_PUBLIC_PATH}/tree/treedepthfirstiterator.h
	${TARGET_PUBLIC_PATH}/tree/treedepthfirstiterator.hpp
	${TARGET_PUBLIC_PATH}/tree/treeiterator.h
	${TARGET_PUBLIC_PATH}/tree/treeleafiterator.h
	${TARGET_PUBLIC_PATH}/tree/treenode.h
)

set(TARGET_PRIVATE_SOURCES
	${TARGET_PRIVATE_PATH}/chunk/cms_volumechunk.cpp
	${TARGET_PRIVATE_PATH}/chunk/volumechunk.cpp
	${TARGET_PRIVATE_PATH}/chunk/volumechunkloadrequest.cpp
	${TARGET_PRIVATE_PATH}/chunk/volumechunkloader.cpp
	${TARGET_PRIVATE_PATH}/components/volumecomponent.cpp
	${TARGET_PRIVATE_PATH}/isosurface/isosurface.cpp
	${TARGET_PRIVATE_PATH}/isosurface/marchingcubessurface.cpp
	${TARGET_PRIVATE_PATH}/isosurface/marchingsquaressurface.cpp
	${TARGET_PRIVATE_PATH}/source/csg/csgsphere.cpp
	${TARGET_PRIVATE_PATH}/source/csg/operations/csgdifference.cpp
	${TARGET_PRIVATE_PATH}/source/csg/operations/csgintersect.cpp
	${TARGET_PRIVATE_PATH}/source/csg/operations/csgnegate.cpp
	${TARGET_PRIVATE_PATH}/source/csg/operations/csgscale.cpp
	${TARGET_PRIVATE_PATH}/source/csg/operations/csgunion.cpp
	${TARGET_PRIVATE_PATH}/source/noise/simplexnoised.cpp
	${TARGET_PRIVATE_PATH}/source/volumebase.cpp
	${TARGET_PRIVATE_PATH}/volumeterrain.cpp
    ${TARGET_PRIVATE_PATH}/volumesystem.cpp
)