set(onyx_TARGET_PUBLIC_DEPENDENCIES
    onyx-core
    onyx-assets
    onyx-filesystem
    onyx-graphicscore
    onyx-input
    onyx-localization
    onyx-profiler
    ImGui
    ImGuizmo
    ImGuiNodeEditor
    ImGuiPlot2D
    ImGuiPlot3D
)