set(onyx_TARGET_PUBLIC_SOURCES
    uimodule.h
    ui_localization.h
    imguinotify.h
    imguisystem.h
    imguiwindow.h
    notificationsystem.h
    propertygrid.h
    propertyinspector.h
    scopedcolor.h
    scopeddisable.h
    scopedid.h
    scopedindent.h
    scopedstyle.h
    widgets.h
    controls/assetselector.h
    controls/button.h
    controls/colorcontrol.h
    controls/combobox.h
    controls/dockspace.h
    controls/treeview.h
    controls/vectorcontrol.h
    layout/imguilayout.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    uimodule.cpp
    ui_localization.cpp
    imguisystem.cpp
    imguiwindow.cpp
    notificationsystem.cpp
    propertygrid.cpp
    scopedcolor.cpp
    scopeddisable.cpp
    scopedid.cpp
    scopedindent.cpp
    scopedstyle.cpp
    widgets.cpp
    controls/assetselector.cpp
    controls/button.cpp
    controls/colorcontrol.cpp
    controls/combobox.cpp
    controls/dockspace.cpp
    controls/treeview.cpp
    controls/vectorcontrol.cpp
    layout/imguilayout.cpp
)