//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated.
//     Do not edit this file directly. Any changes will be overwritten
//     with the next build.
// </auto-generated>
//------------------------------------------------------------------------------
#include <onyx/ui/propertygrid.h>
#include <onyx/ui/scopeddisable.h>
#include <onyx/gamecore/components/freecameracomponent.gen.h>

namespace Onyx::GameCore
{
    bool FreeCameraControllerComponent::DrawProperties(bool /*forceShow*/)
    {
        using namespace Ui;
        bool isModified = false;
        isModified |= PropertyGrid::DrawProperty("BaseVelocity", BaseVelocity);
        isModified |= PropertyGrid::DrawProperty("MinVelocity", MinVelocity);
        isModified |= PropertyGrid::DrawProperty("MaxVelocity", MaxVelocity);
        isModified |= PropertyGrid::DrawProperty("RotationVelocity", RotationVelocity);
        isModified |= PropertyGrid::DrawProperty("VelocityIncrementFactor", VelocityIncrementFactor);
        return isModified;
    }
    bool FreeCameraRuntimeComponent::DrawProperties(bool /*forceShow*/)
    {
        using namespace Ui;
        bool isModified = false;
        isModified |= PropertyGrid::DrawProperty("InputDirection", InputDirection);
        isModified |= PropertyGrid::DrawProperty("InputRotation", InputRotation);
        isModified |= PropertyGrid::DrawProperty("Velocity", Velocity);
        isModified |= PropertyGrid::DrawProperty("Pitch", Pitch);
        isModified |= PropertyGrid::DrawProperty("Yaw", Yaw);
        isModified |= PropertyGrid::DrawProperty("PitchDelta", PitchDelta);
        isModified |= PropertyGrid::DrawProperty("YawDelta", YawDelta);
        return isModified;
    }
}

