//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated.
//     Do not edit this file directly. Any changes will be overwritten
//     with the next build.
// </auto-generated>
//------------------------------------------------------------------------------
#include <onyx/ui/propertygrid.h>
#include <onyx/ui/scopeddisable.h>
#include <onyx/gamecore/components/namecomponent.gen.h>

namespace Onyx::GameCore
{
    bool NameComponent::DrawProperties(bool /*forceShow*/)
    {
        using namespace Ui;
        bool isModified = false;
        
        {
            ScopedImGuiDisabled _;
            isModified |= PropertyGrid::DrawProperty("Name", Name);
        }
        return isModified;
    }
}

