//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated.
//     Do not edit this file directly. Any changes will be overwritten
//     with the next build.
// </auto-generated>
//------------------------------------------------------------------------------
#include <onyx/ui/propertygrid.h>
#include <onyx/ui/scopeddisable.h>
#include <onyx/gamecore/components/transformcomponent.gen.h>

namespace Onyx::GameCore
{
    bool TransformComponent::DrawProperties(bool forceShow)
    {
        using namespace Ui;
        bool isModified = false;
        isModified |= PropertyGrid::DrawProperty("Translation", Translation);
        {
            auto displayUnit = QuantityCast<Units::Degrees, Units::Radians>(RotationEuler);
            if( PropertyGrid::DrawProperty("Rotation", displayUnit) )
            {
                RotationEuler = QuantityCast<Units::Radians, Units::Degrees>(displayUnit);
                isModified = true;
            }
        }
        isModified |= PropertyGrid::DrawProperty("Scale", Scale);
        if (forceShow)
        {
            isModified |= PropertyGrid::DrawProperty("Rotation", Rotation);
        }
        return isModified;
    }
}

