set(onyx_TARGET_PUBLIC_SOURCES
    platformcontext.h
    platformfwd.h
    platformsystem.h
    window.h
    windowsettings.h
    linux/wayland/waylandplatformcontext.h
    linux/wayland/waylandwindow.h
    linux/wayland/waylandinput.h
    linux/wayland/waylandpointer.h
    linux/wayland/waylandkeyboard.h
    windows/gameinputcontroller.h
    windows/windowskeycodes.h
    windows/windowsplatformcontext.h
    windows/windowswindow.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    platformsystem.cpp
    windowsettings.cpp
    linux/wayland/waylandplatformcontext.cpp
    linux/wayland/waylandwindow.cpp
    linux/wayland/waylandinput.cpp
    linux/wayland/waylandpointer.cpp
    linux/wayland/waylandkeyboard.cpp
    windows/gameinputcontroller.cpp
    windows/windowsplatformcontext.cpp
    windows/windowswindow.cpp
)