set(onyx_TARGET_PUBLIC_SOURCES
    application.h
    debug/gui/statusbaroverlay.h
    debug/gui/keyboardoverlay.h
    debug/gui/notificationloggersink.h
    debug/gui/fpsstatusbaritem.h
    graphics/meshsourceasset.h
    log/logsinkfile.h
    taskgraph/taskgraph.h
    taskgraph/taskgraphtask.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    application.cpp
    debug/gui/statusbaroverlay.cpp
    debug/gui/keyboardoverlay.cpp
    debug/gui/notificationloggersink.cpp
    debug/gui/fpsstatusbaritem.cpp
    graphics/meshsourceasset.cpp
    log/logsinkfile.cpp
    platform/windows/main.cpp
    taskgraph/taskgraph.cpp
    taskgraph/taskgraphtask.cpp
)