set(onyx_TARGET_PUBLIC_SOURCES
    filedialog.h
    filestream.h
    filewatcher.h
    imagefile.h
    onyx_filesystem_pch.h
    onyxfile.h
    path.h
    jsonserializer.h
    jsondeserializer.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    filedialog.cpp
    filestream.cpp
    filewatcher.cpp
    imagefile.cpp
    onyx_filesystem.cpp
    onyxfile.cpp
    path.cpp
    jsonserializer.cpp
    jsondeserializer.cpp
)