set(onyx_TARGET_PUBLIC_SOURCES
    assets/meshasset.h
    font/sdffont.h
    rendergraph/rendergraph.h
    rendergraph/rendergraphnodefactory.h
    rendergraph/rendergraphtask.h
    rendergraph/tasks/atmosphericskytask.h
    rendergraph/tasks/debuglightclusterspass.h
    rendergraph/tasks/multiplescatteringtask.h
    rendergraph/tasks/updatelightclusterstask.h
    rendergraph/tasks/updateviewconstantstask.h
    rendergraph/tasks/scatteringtask.h
    rendergraph/tasks/skyviewluttask.h
    rendergraph/tasks/tonemappass.h
    scattering/scattering.h
    serialize/materialshadergraphserializer.h
    serialize/meshserializer.h
    serialize/rendergraphserializer.h
    serialize/sdffontserializer.h
    serialize/shadergraphserializer.h
    serialize/shaderserializer.h
    serialize/textureserializer.h
    shadergraph/shadergraph.h
    shadergraph/materialshadergraph.h
    shadergraph/postprocessshadergraph.h
    shadergraph/shadergraphnode.h
    shadergraph/shadergraphnodefactory.h
    shadergraph/nodes/fragmentshaderoutnode.h
    shadergraph/nodes/getworldnormal.h
    shadergraph/nodes/getworldposition.h
    shadergraph/nodes/sampletexturenode.h
    shadergraph/nodes/math/arithmeticnodes.h
    shadergraph/nodes/math/geometricnodes.h
    shadergraph/nodes/math/simplexnoisenode.h
    shadergraph/nodes/math/vectornodes.h
)

set(onyx_TARGET_PRIVATE_SOURCES
    assets/meshasset.cpp
    textureasset.cpp
    rendergraph/rendergraph.cpp
    rendergraph/rendergraphtask.cpp
    rendergraph/rendergraphnodefactory.cpp
    rendergraph/tasks/atmosphericskytask.cpp
    rendergraph/tasks/debuglightclusterspass.cpp
    rendergraph/tasks/multiplescatteringtask.cpp
    rendergraph/tasks/updatelightclusterstask.cpp
    rendergraph/tasks/updateviewconstantstask.cpp
    rendergraph/tasks/scatteringtask.cpp
    rendergraph/tasks/skyviewluttask.cpp
    rendergraph/tasks/tonemappass.cpp
    serialize/materialshadergraphserializer.cpp
    serialize/meshserializer.cpp 
    serialize/rendergraphserializer.cpp
    serialize/sdffontserializer.cpp
    serialize/shadergraphserializer.cpp
    serialize/shaderserializer.cpp
    serialize/textureserializer.cpp
    shadergraph/shadergraph.cpp
    shadergraph/shadergraphnodefactory.cpp
    shadergraph/nodes/fragmentshaderoutnode.cpp
    shadergraph/nodes/getworldnormal.cpp
    shadergraph/nodes/getworldposition.cpp
    shadergraph/nodes/sampletexturenode.cpp
    shadergraph/nodes/shadergraphnodes.cpp
    shadergraph/nodes/math/simplexnoisenode.cpp
)